version: '3.8'  # Specify the version of Docker Compose being used

services:
  studio:
    build:
      context: ../..  # Build context for the Docker image
      dockerfile: apps/studio/Dockerfile  # Path to the Dockerfile
      target: production  # Target build stage
    ports:
      - "3000:3000"  # Map port 3000 of the container to port 3000 of the host
    extra_hosts:
      - 'host.docker.internal:host-gateway'  # Allows access to the host from the container
    environment:
      # Environment variables
      - PALICO_AGENT_API_URL=http://host.docker.internal:8000  # API URL for the agent
      - PALICO_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MTM4MDg3NzB9.GEskObwga-XXXvTM8V6v2d27RNb9-Y8em0Kim5Zazpg  # Service key
    volumes:
      - ./studio-data:/usr/src/app/data  # Mount a local volume for persistent data storage
    networks:
      - studio_network  # Assign to a specific network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]  # Check if the service is healthy
      interval: 30s  # Time between health checks
      timeout: 10s  # Max time before considering it unhealthy
      retries: 3  # Number of failed attempts before marking as unhealthy

networks:
  studio_network:
    driver: bridge  # Use the bridge network driver for internal communication between services
